// <auto-generated />
using System;
using ActielijstApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActielijstApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408092857_AddProjectAssignmentsAndRelatedTables")]
    partial class AddProjectAssignmentsAndRelatedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActielijstApi.Models.AankomendeInspectie", b =>
                {
                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumGereed")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraMedewerker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspecteurId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opdracht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PSID")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoortId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Toegekend")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Toegewezen")
                        .HasColumnType("bit");

                    b.Property<decimal?>("fldBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("fldContactpersoonId")
                        .HasColumnType("int");

                    b.Property<int?>("fldOpdrachtgeverId")
                        .HasColumnType("int");

                    b.Property<string>("fldSGG")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_AankomendeInspecties", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.Actie", b =>
                {
                    b.Property<int>("FldMid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FldMid"));

                    b.Property<DateTime?>("FldMActieDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FldMActieGereed")
                        .HasColumnType("datetime2");

                    b.Property<string>("FldMActieSoort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FldMActieVoor")
                        .HasColumnType("int");

                    b.Property<int?>("FldMActieVoor2")
                        .HasColumnType("int");

                    b.Property<string>("FldMAfspraak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FldMContactPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FldMDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FldMKlantId")
                        .HasColumnType("int");

                    b.Property<int?>("FldMOfferteId")
                        .HasColumnType("int");

                    b.Property<int?>("FldMPrioriteit")
                        .HasColumnType("int");

                    b.Property<int?>("FldMProjectId")
                        .HasColumnType("int");

                    b.Property<string>("FldOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FldOpdrachtId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("WerknId")
                        .HasColumnType("int");

                    b.HasKey("FldMid");

                    b.ToTable("tblMemo", "dbo");
                });

            modelBuilder.Entity("ActielijstApi.Models.ActieSoort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stblActieSoort", "dbo");
                });

            modelBuilder.Entity("ActielijstApi.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Attentie")
                        .HasColumnType("bit");

                    b.Property<string>("Bedrijf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BEDRIJF");

                    b.Property<int?>("Bedrijfsadresid")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrijskoppeling")
                        .HasColumnType("int");

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Cursist")
                        .HasColumnType("bit");

                    b.Property<int?>("CursistId")
                        .HasColumnType("int");

                    b.Property<int?>("Cursistnr")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumCursusdoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumJaarMon1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumJaarMon2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumJaarMon3")
                        .HasColumnType("datetime2");

                    b.Property<string>("Debiteurnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deelnemer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAanmaning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("E-MAIL_ADR");

                    b.Property<string>("EmailFactuur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Esteco")
                        .HasColumnType("bit");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirstContactId")
                        .HasColumnType("int");

                    b.Property<string>("FldWebSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geachte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GebDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("GebDatumOud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GebPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardSoft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KiwaContactId")
                        .HasColumnType("int");

                    b.Property<string>("KiwaNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Klantnum")
                        .HasColumnType("int");

                    b.Property<string>("KomOhouder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Leverancier")
                        .HasColumnType("bit");

                    b.Property<string>("LoginNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeldSoort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobelTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrSgg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("Omschr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postadres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roepnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sofinummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SsmaTimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TekstJaarMon1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TekstJaarMon2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TekstJaarMon3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelPrive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tussenvoegsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VestigAdr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VestigPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VestigPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voorletters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voorvoegsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wpl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zoekcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("adres", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.Correspondentie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantID")
                        .HasColumnType("int")
                        .HasColumnName("KlantID");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("fldAan")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBijlage")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBijlage2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBijlage3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fldCC")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorAuteur")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("fldCorAuteur");

                    b.Property<string>("fldCorBestand")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("fldCorBestand");

                    b.Property<int?>("fldCorCPersId")
                        .HasColumnType("int")
                        .HasColumnName("fldCorCPersId");

                    b.Property<int?>("fldCorConsultancyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fldCorDatum")
                        .HasColumnType("datetime2")
                        .HasColumnName("fldCorDatum");

                    b.Property<DateTime?>("fldCorDatum2")
                        .HasColumnType("datetime2");

                    b.Property<string>("fldCorExtensie")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorFactuurId")
                        .HasColumnType("int");

                    b.Property<string>("fldCorGeachte")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorKenmerk")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorOffNum")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorOmschrijving")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("fldCorOmschrijving");

                    b.Property<int?>("fldCorOpdrachtNum")
                        .HasColumnType("int")
                        .HasColumnName("fldCorOpdrachtNum");

                    b.Property<string>("fldCorProgramma")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorProjNum")
                        .HasColumnType("int")
                        .HasColumnName("fldCorProjNum");

                    b.Property<int?>("fldCorSoort")
                        .HasColumnType("int");

                    b.Property<string>("fldCorTav")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorTrainingId")
                        .HasColumnType("int");

                    b.Property<string>("fldFrom")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldSjabloon")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("correspondentie", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.CorrespondentieFields", b =>
                {
                    b.Property<string>("AanmaningEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aannemer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AannemerAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AannemerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AannemerLand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AannemerPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AannemerPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AannemerTelefoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bedrijf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedrijfEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Betreft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ContractBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractLooptijd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contractnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrespondentieNr")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EindDatumContract")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactuurEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factuurmaand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JaarIndexering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kenmerk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnderwerpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OpdrachtBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpdrachtHuisnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SjabloonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SjabloonNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SjabloonOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UitvoerDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UitvoerDatumKort")
                        .HasColumnType("datetime2");

                    b.Property<string>("Verwerker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerwerkerAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerwerkerGeachte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerwerkerLand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerwerkerPCPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerwerkerTAV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerwerkerTelefoon")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_CorrespondentieFields", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.Globals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiefPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("archiefpath");

                    b.Property<string>("DesignPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("designpath");

                    b.Property<bool>("DisplayMailVoorVerzenden")
                        .HasColumnType("bit")
                        .HasColumnName("DisplayMailVoorVerzenden");

                    b.Property<string>("FactuurAccount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FactuurAccount");

                    b.Property<bool>("FactuurHandtekening")
                        .HasColumnType("bit")
                        .HasColumnName("FactuurHandtekening");

                    b.Property<string>("FactuurText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FactuurText");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FotoPath");

                    b.Property<string>("KiwaPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KiwaPath");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pdfPath");

                    b.Property<string>("ProjectPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectPath");

                    b.Property<string>("SavePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("savepath");

                    b.Property<string>("ScanPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ScanPath");

                    b.Property<string>("SjabloonPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sjabloonpath");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("tblGlobals", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.Inspectie", b =>
                {
                    b.Property<int>("OpdrachtId")
                        .HasColumnType("int");

                    b.Property<string>("Applicateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelNotitie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("ExtraMedewerker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KiwaNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtHuisnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlanJaar")
                        .HasColumnType("int");

                    b.Property<int?>("Toegewezen")
                        .HasColumnType("int");

                    b.Property<int?>("fldAantalM2")
                        .HasColumnType("int");

                    b.Property<decimal?>("fldBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("fldCertKeuring")
                        .HasColumnType("bit");

                    b.Property<int?>("fldContactpersoonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fldDatumGereed")
                        .HasColumnType("datetime2");

                    b.Property<string>("fldExternNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fldGereedVoor")
                        .HasColumnType("datetime2");

                    b.Property<bool>("fldKiwaCert")
                        .HasColumnType("bit");

                    b.Property<int?>("fldKiwaKeuringsNr")
                        .HasColumnType("int");

                    b.Property<decimal?>("fldMaandBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("fldOpdrachtId")
                        .HasColumnType("int");

                    b.Property<string>("fldOpdrachtStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fldOpdrachtgeverId")
                        .HasColumnType("int");

                    b.Property<string>("fldPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fldPlanDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("fldProjectId")
                        .HasColumnType("int");

                    b.Property<string>("fldProjectLeider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fldProjectNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fldProjectNummer")
                        .HasColumnType("int");

                    b.Property<string>("fldSGG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fldSoort")
                        .HasColumnType("int");

                    b.Property<int?>("fldStatus")
                        .HasColumnType("int");

                    b.Property<int?>("fldVerwerkendBedrijf")
                        .HasColumnType("int");

                    b.Property<string>("fldjaar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OpdrachtId");

                    b.ToTable((string)null);

                    b.ToView("vw_KIWAInspecties", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FldAantalM2")
                        .HasColumnType("int")
                        .HasColumnName("fldAantalM2");

                    b.Property<string>("FldActie")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldActie");

                    b.Property<string>("FldAdres")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldAdres");

                    b.Property<string>("FldAfdeling")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldAfdeling");

                    b.Property<string>("FldAfwerking")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldAfwerking");

                    b.Property<bool>("FldArchiefMap")
                        .HasColumnType("bit")
                        .HasColumnName("fldArchiefMap");

                    b.Property<DateTime?>("FldDatum")
                        .HasColumnType("datetime2")
                        .HasColumnName("fldDatum");

                    b.Property<string>("FldEPA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldEPA");

                    b.Property<string>("FldExternNummer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldExternNummer");

                    b.Property<string>("FldExternNummer2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldExternNummer2");

                    b.Property<string>("FldFabrikant")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldFabrikant");

                    b.Property<string>("FldFolder")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldFolder");

                    b.Property<string>("FldIntracNr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldIntracNr");

                    b.Property<string>("FldJaar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldjaar");

                    b.Property<string>("FldKiWa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldKiWa");

                    b.Property<bool>("FldKiwaCert")
                        .HasColumnType("bit")
                        .HasColumnName("fldKiwaCert");

                    b.Property<string>("FldOpdrachtgever")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldOpdrachtgever");

                    b.Property<string>("FldOpdrachtgeverId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldOpdrachtgeverId");

                    b.Property<string>("FldPC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldPC");

                    b.Property<string>("FldPlaats")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldPlaats");

                    b.Property<int?>("FldPrevProjectId")
                        .HasColumnType("int")
                        .HasColumnName("fldPrevProjectId");

                    b.Property<string>("FldProjectNaam")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldProjectNaam");

                    b.Property<int?>("FldProjectNummer")
                        .HasColumnType("int")
                        .HasColumnName("fldProjectNummer");

                    b.Property<string>("FldSGG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldSGG");

                    b.Property<string>("FldSoort")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldSoort");

                    b.Property<string>("FldStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldStatus");

                    b.Property<string>("FldSysteem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldSysteem");

                    b.Property<int?>("FldVerwerkendBedrijf")
                        .HasColumnType("int")
                        .HasColumnName("fldVerwerkendBedrijf");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("SSMA_TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("tblprojecten", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.ProjectOnderdeel", b =>
                {
                    b.Property<int>("fldProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fldProjectId"));

                    b.HasKey("fldProjectId");

                    b.ToTable("tblProjectOnderdelen", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.StandaardDoc", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doc_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocId"));

                    b.Property<int?>("DocNum")
                        .HasColumnType("int")
                        .HasColumnName("fldDocNum");

                    b.Property<string>("DocOmschrijving")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldDocOmschrijving");

                    b.Property<string>("DocPrefix")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldDocPrefix");

                    b.Property<string>("DocSavePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldDocSavePath");

                    b.Property<string>("EmailAan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldEmailAan");

                    b.Property<string>("EmailSjabloon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldEmailSjabloon");

                    b.Property<string>("EmailSubject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldEmailSubject");

                    b.Property<string>("NaamDoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldNaamDoc");

                    b.Property<string>("PathDoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldPathDoc");

                    b.Property<int?>("PrijsId")
                        .HasColumnType("int")
                        .HasColumnName("fldPrijsId");

                    b.Property<string>("ProjectMap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fldProjectMap");

                    b.Property<int?>("Soort")
                        .HasColumnType("int")
                        .HasColumnName("fldSoort");

                    b.HasKey("DocId");

                    b.ToTable("tblStandaardDoc", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.StblCorrespondentieField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrespondentieId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplaceString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standaardwaarde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Veld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeldType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stblCorrespondentieFields", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Models.StblPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("stblPriority", "dbo");
                });

            modelBuilder.Entity("ActielijstApi.Models.Werknemer", b =>
                {
                    b.Property<int>("WerknId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WerknId"));

                    b.Property<DateTime?>("FldDatumUitDienst")
                        .HasColumnType("datetime2");

                    b.Property<string>("FldLoginNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initialen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WerknId");

                    b.ToTable("Werknemers", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
