// <auto-generated />
using System;
using ActielijstApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActielijstApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActielijstApi.Data.AankomendeInspectie", b =>
                {
                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumGereed")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraMedewerker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspecteurId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opdracht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PSID")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoortId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Toegekend")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Toegewezen")
                        .HasColumnType("bit");

                    b.Property<decimal?>("fldBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("fldContactpersoonId")
                        .HasColumnType("int");

                    b.Property<int?>("fldOpdrachtgeverId")
                        .HasColumnType("int");

                    b.Property<string>("fldSGG")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_AankomendeInspecties", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Data.ActieSoort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stblActieSoort", "dbo");
                });

            modelBuilder.Entity("ActielijstApi.Data.Correspondentie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantID")
                        .HasColumnType("int");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("fldAan")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBijlage")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBijlage2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBijlage3")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fldCC")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorAuteur")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorBestand")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorCPersId")
                        .HasColumnType("int");

                    b.Property<int?>("fldCorConsultancyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fldCorDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fldCorDatum2")
                        .HasColumnType("datetime2");

                    b.Property<string>("fldCorExtensie")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorFactuurId")
                        .HasColumnType("int");

                    b.Property<string>("fldCorGeachte")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorKenmerk")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorOffNum")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldCorOmschrijving")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorOpdrachtNum")
                        .HasColumnType("int");

                    b.Property<string>("fldCorProgramma")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorProjNum")
                        .HasColumnType("int");

                    b.Property<int?>("fldCorSoort")
                        .HasColumnType("int");

                    b.Property<string>("fldCorTav")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("fldCorTrainingId")
                        .HasColumnType("int");

                    b.Property<string>("fldFrom")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("fldSjabloon")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("correspondentie", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Data.Inspectie", b =>
                {
                    b.Property<int>("OpdrachtId")
                        .HasColumnType("int");

                    b.Property<string>("Applicateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelNotitie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("ExtraMedewerker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KiwaNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtHuisnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpdrachtPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlanJaar")
                        .HasColumnType("int");

                    b.Property<int?>("Toegewezen")
                        .HasColumnType("int");

                    b.Property<int?>("fldAantalM2")
                        .HasColumnType("int");

                    b.Property<decimal?>("fldBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("fldCertKeuring")
                        .HasColumnType("bit");

                    b.Property<int?>("fldContactpersoonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fldDatumGereed")
                        .HasColumnType("datetime2");

                    b.Property<string>("fldExternNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fldGereedVoor")
                        .HasColumnType("datetime2");

                    b.Property<bool>("fldKiwaCert")
                        .HasColumnType("bit");

                    b.Property<int?>("fldKiwaKeuringsNr")
                        .HasColumnType("int");

                    b.Property<decimal?>("fldMaandBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("fldOpdrachtId")
                        .HasColumnType("int");

                    b.Property<string>("fldOpdrachtStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fldOpdrachtgeverId")
                        .HasColumnType("int");

                    b.Property<string>("fldPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fldPlanDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("fldProjectId")
                        .HasColumnType("int");

                    b.Property<string>("fldProjectLeider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fldProjectNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fldProjectNummer")
                        .HasColumnType("int");

                    b.Property<string>("fldSGG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fldSoort")
                        .HasColumnType("int");

                    b.Property<int?>("fldStatus")
                        .HasColumnType("int");

                    b.Property<int?>("fldVerwerkendBedrijf")
                        .HasColumnType("int");

                    b.Property<string>("fldjaar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OpdrachtId");

                    b.ToTable((string)null);

                    b.ToView("vw_KIWAInspecties", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Data.Memo", b =>
                {
                    b.Property<int>("FldMid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FldMid"));

                    b.Property<DateTime?>("FldMActieDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("FldMActieSoort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FldMActieVoor")
                        .HasColumnType("int");

                    b.Property<int?>("FldMActieVoor2")
                        .HasColumnType("int");

                    b.Property<string>("FldMAfspraak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FldMContactPers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FldMDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FldMKlantId")
                        .HasColumnType("int");

                    b.Property<int?>("FldMOfferteId")
                        .HasColumnType("int");

                    b.Property<int?>("FldMPrioriteit")
                        .HasColumnType("int");

                    b.Property<int?>("FldMProjectId")
                        .HasColumnType("int");

                    b.Property<string>("FldOmschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FldOpdrachtId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("WerknId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fldMActieGereed")
                        .HasColumnType("datetime2");

                    b.HasKey("FldMid");

                    b.ToTable("tblMemo", "dbo");
                });

            modelBuilder.Entity("ActielijstApi.Data.ProjectOnderdeel", b =>
                {
                    b.Property<int>("fldProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fldProjectId"));

                    b.HasKey("fldProjectId");

                    b.ToTable("tblProjectOnderdelen", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Data.StblCorrespondentieField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrespondentieId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplaceString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standaardwaarde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Veld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeldType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stblCorrespondentieFields", (string)null);
                });

            modelBuilder.Entity("ActielijstApi.Data.StblPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("stblPriority", "dbo");
                });

            modelBuilder.Entity("ActielijstApi.Data.Werknemer", b =>
                {
                    b.Property<int>("WerknId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WerknId"));

                    b.Property<string>("FldLoginNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initialen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WerknId");

                    b.ToTable("Werknemers", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
